/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.ParametresTest;
import java.io.BufferedReader;
import java.io.FileReader;
import static java.time.Clock.system;
import javax.swing.JFileChooser;

/**
 *
 * @author Oscar Teamatio
 */
public class Load extends javax.swing.JFrame {

    /**
     * Creates new form Load
     */
    public ParametresTest params = new ParametresTest();
    //Save sv =new Save(null, null, null, null, null, null, null, null, null, null);
   
    public Load() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Chemin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/aproposIcon.jpg"))); // NOI18N
        jButton1.setText("Parcourir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Chemin:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void readFile(String filePath){
      try {
         
            BufferedReader reader = new BufferedReader(new FileReader(filePath));
            String ligne;
            while((ligne = reader.readLine()) != null){
                 if(ligne.startsWith("Nature ")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(9, 12));
                    params.setNature(ligne.substring(9, 12));
                     

                    //System.out.println("Bonjour");
                }
                if(ligne.startsWith("Valeur Initiale:")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(17, 19));
                    
                }
                 if(ligne.startsWith("Nombre ")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(7, 8));
//                    params.setNombredEssai(Integer.parseInt(ligne.substring(7, 8)));
                     
                }
                  if(ligne.startsWith("Vitesse :")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(10, 11));
                    params.setVitesse(Double.parseDouble(ligne.substring(10, 11)));
                      
                }
                   if(ligne.startsWith("Aléaroire:")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(11, 14));
                    if ("OUI".equals(ligne.substring(11, 14))){
                        params.setAleatoire(true);
                    }else {
                        params.setAleatoire(false);
                    }
                   
                } 
                    //String a = " ";
                    if(ligne.startsWith("ESSAI CADRE")){
                     
                            String toto = ligne.split(" ")[2];
                            toto = toto.substring(1, toto.length() - 1);
                            
                            String[] tata = toto.split(";");
                           int len_A = tata.length;
                           System.out.println("len_A"+len_A);
                           int[] A = new int[len_A] ; 
                            for (String t: tata) {
                               System.out.println(t);
                                System.out.println("i :"+i);
                               A[i]= Integer.parseInt(t);
                               // System.out.println(t);
                                i=i+1;
                            }
                            System.out.println("A[0] : "+A[0]);
                            params.setValeursCadre(A);
                               

                             
                } 
                    if(ligne.startsWith("ESSAI TIGE")){
                     
                            String toto = ligne.split(" ")[2];
                            toto = toto.substring(1, toto.length() - 1);
                            
                            String[] tata = toto.split(";");
                           int len_A = tata.length;
                           System.out.println("len_A"+len_A);
                           int[] A = new int[len_A] ; 
                            for (String t: tata) {
                               System.out.println(t);
                                System.out.println("i :"+i);
                               A[i]= Integer.parseInt(t);
                               // System.out.println(t);
                                i=i+1;
                            }
                            
                            System.out.println("A[0] : "+A[0]);
                            params.setValeursTige(A);
                               

                             
                } 
                
            }
        } catch (Exception ex){
            System.err.println("Error. "+ex.getMessage());
        }

    }
    
    public void save(){
        if (params.getNature()== "RFT"){
            
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
         JFileChooser ch=new JFileChooser();
         int var = ch .showOpenDialog(null);
         Chemin.setText(ch.getSelectedFile().getAbsolutePath());
         readFile(ch.getSelectedFile().getAbsolutePath());*/
       
        //save();
      //  Save svr = new Save();
       // svr.setVisible(true);
         params.setNature(Chemin.getText());
         ValeurCadre l = new ValeurCadre();
         l.setVisible(true);
         dispose();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }
    
    int i;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Chemin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
