/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

placer en amont le choix du test 
changer le nom en Bguette 
  placer deux label dans une fennetres pour fixer les valeurs zeo 
inclur ela posibilité de supprimer une ligne ou d'ajoujouter en remplacant le bouton nouveau par un plus  
entrer les valeurs des tableaux alignés sur la droite
Rajouter le fomrmat de présentation
Remplacer le label nombre d'essais par un bouton.
Remplacer le bouton par lancer le test
1- placer la bguette à la verticale (mannete)
2- indiquer la valeur de reference
Bouton valider
Titre du label Evaluation de l'orientation spation spatiale
Remaplacer lature par test 
REmplacer Essai par orientation intiale 
Remplacer Aléatoire tige par ordre orientation baguette
Remplacer Zéro par valeur de réference 
creer pour le fichier résultats  tout sous forme de ligne
enlever la fenetre epour le cas VVS  et pour RFT*/
package Interfaces;

import Classes.Parametre;
import arduino.Arduino;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Tematio
 */
public class Save extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Parametre params = new Parametre();
    
    Writer conf;
    FileWriter config;
    String a = " vv" ;
    Arduino ardu = new Arduino();
    
    public Save(){
       
                setBackground(Color.WHITE);

        initComponents();
        
        
         safe();
         CadrePnl.setVisible(false);
         setTitle("Configuration");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Oscar Teamatio\\Documents\\NetBeansProjects\\Devah\\src\\picture\\devah.png"));
        ardu.setPortDescription("COM7");
        ardu.setBaudRate(57600);
     
     
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*************************************************************************************************************************************/
      public void safe(){
        if (RFTCheck.isSelected()){
            
            a= "RFT";       
        }else if (VVSCheck.isSelected()){
            a="VVS";
        }else if(AxeCheck.isSelected()){
            a="AXE-Z";
        }
        params.setNature(a);
        if (AleatoireCheckTige.isSelected()){
            c="OUI";
        }else if (ContinueCheckTige.isSelected()){
            c="NON";
        }
        
        if(AleatoireCheckCadre.isSelected()){
            b="OUI";
            
        }else if (ContinueCheckCadre.isSelected()){
            b="NON";
        }
    }
      
      
/*******************************************************************************************************************************************/
      public void erreur(){
          if(RFTCheck.isSelected()==false && VVSCheck.isSelected()==false && AxeCheck.isSelected()==false){
              ErreurNature.setVisible(true);
          }
          if(("").equals(NombreEssaiTige.getText())){
              ErreurNbTige.setVisible(true);
          }
          if(RFTCheck.isSelected()){
          if(("").equals(NombreEssaiCadre.getText())){
              ErreurNbCadre.setVisible(true);
          }
          if(AleatoireCheckCadre.isSelected()==false && ContinueCheckCadre.isSelected()==false){
              ErreurACadre.setVisible(true);
          }
          }
          if(AleatoireCheckTige.isSelected()==false && ContinueCheckTige.isSelected()==false){
              ErreurATige.setVisible(true);
          }
          
         if(("").equals(Vitesse.getText())){
              ErreurVitesse.setVisible(true);
          } 
          
      }
      
/*******************************************************************************************************************************************/
      public static int[] fusion ( int[] tab1, int[]tab2 )
    {
        int tab3[]= new int[tab1.length+tab2.length];
       
        System.arraycopy(tab1, 0, tab3,0,tab1.length);
        System.arraycopy(tab2,0, tab3,tab1.length, tab2.length);
        
        return tab3;
    }
 /*/***************************************************************************************************************************************/     
      public void Alea(){
         
          int j=EssaisTige.getRowCount()*Integer.parseInt(NombreEssaiTige.getText());
           Vector<Integer> B = new Vector<Integer>();
           Vector<Integer> C = new Vector<Integer>();
           
            int AngleCA []= new int[0];
             
            int AngleTige []= new int[EssaisTige.getRowCount()];
            int AngleTA []= new int [0];
            int AngleTiges[]= new int [j];
      if(RFTCheck.isSelected()){     
             int k=EssaisCadre.getRowCount()*Integer.parseInt(NombreEssaiCadre.getText());
             int AngleCadres[]=new int[k];
             int AngleCadre []= new int[EssaisCadre.getRowCount()];
            for(int i=0 ;i<EssaisCadre.getRowCount();i++){
                AngleCadre[i] =Integer.parseInt((String) EssaisCadre.getModel().getValueAt(i, 0));
            }
             for(int p=0;p<Integer.parseInt(NombreEssaiCadre.getText());p++){
              AngleCA = fusion(AngleCA,AngleCadre); 
            }
            
        if(AleatoireCheckCadre.isSelected()){
         
          for (int u=0;u<AngleCA.length;u++){
              C.addElement(AngleCA[u]);
          }
          System.out.println(C);
          
          Random ran = new Random();
          //int index=ran.nextInt(C.size());
          
          for (int u=0;u<AngleCA.length;u++){
              //on choisit l'index aléatoire 
              int index=ran.nextInt(C.size());
              System.out.println(C.get(index)+"  "+ index);
              //on ajoute la valeur dans le Tableau 
              AngleCadres[u]= C.get(index);
              //on supprime ce qu'on vient de mettre 
              C.remove(index);
          }
           
          
           System.out.println(Arrays.toString(AngleCadres));
           params.setValeursCadre(AngleCadres);
        }else{
            Parametre.setValeursCadre(AngleCA);
        }
        params.setNombredEssaiCadre(Integer.parseInt(NombreEssaiCadre.getText()));
      }
        
         
          for(int i=0 ;i<EssaisTige.getRowCount();i++){
                AngleTige[i] =Integer.parseInt((String) EssaisTige.getModel().getValueAt(i, 0));
            }
          for(int p=0;p<Integer.parseInt(NombreEssaiTige.getText());p++){
              AngleTA = fusion(AngleTA,AngleTige); 
            }
          System.out.println(Arrays.toString(AngleTiges));
        if(AleatoireCheckTige.isSelected()){
          for (int u=0;u<AngleTA.length;u++){
              B.addElement(AngleTA[u]);
            }
          
         Random ran = new Random();
          //int index=ran.nextInt(C.size());
          
          for (int u=0;u<AngleTA.length;u++){
              //on choisit l'index aléatoire 
              int index=ran.nextInt(B.size());
              System.out.println(B.get(index)+"  "+ index);
              //on ajoute la valeur dans le Tableau 
              AngleTiges[u]= B.get(index);
              //on supprime ce qu'on vient de mettre 
              B.remove(index);
            }
           
       
          params.setValeursTige(AngleTiges);
          System.out.println(Arrays.toString(AngleTiges));
        }else{
            params.setValeursTige(AngleTA);
        }
      
        params.setNombredEssaiTige(Integer.parseInt(NombreEssaiTige.getText()));
        params.setVitesse(Integer.parseInt(Vitesse.getText()));
        params.setNature(a);
        params.setNombresTotal(e);
    }
      /*******************************************************************************************************************************/
      public void Enregistrement (){
          safe();
           try {
            //Ici on enregistre le fichier
         
           PrintWriter fichier = new PrintWriter("C:\\Users\\Public\\Documents\\Config.txt");
            fichier.println("");
            fichier.println("Test: " +a );
            fichier.println("Vitesse d'ajustement: " + Vitesse.getText());
            fichier.println("-----------------------------------");
            fichier.print("Bag. Orientation init. : [");
            for(i=0;i <EssaisTige.getRowCount();i++){
                if (i!=(EssaisTige.getRowCount()-1)){
                    
                    fichier.print((String) EssaisTige.getModel().getValueAt(i,0)+";");
                } else {
                    fichier.print((String) EssaisTige.getModel().getValueAt(i,0));
                    
                }
            }
            fichier.println("]");
            fichier.println("Bag. Aléatoire: "+c);
            fichier.println("Bag. Nombre de répétition: "+NombreEssaiTige.getText());
            fichier.println("-----------------------------------");
            fichier.print("Cadre Orientation init. : [");
            for(i=0;i <EssaisCadre.getRowCount();i++){
                if (i!=(EssaisCadre.getRowCount()-1)){
                    
                    fichier.print((String) EssaisCadre.getModel().getValueAt(i,0)+";");
                } else {
                    fichier.print((String) EssaisCadre.getModel().getValueAt(i,0));
                    
                }
            }
            fichier.println("]");
            fichier.println("Cadre Aléatoire: "+b);
            fichier.println("Cadre Nombres de répétition: "+NombreEssaiCadre.getText());
            fichier.println("-------------------------------------");
            fichier.println("Nombre d'essai: " +Nombredessai.getText());
            fichier.close();

            
        } catch (Exception ex){
            System.err.println("Error. "+ex.getMessage());
        }
        
      }
    /***************************************************************************************************************************************/
      public  void readFile(String filePath){
      try {
            File fichier = new File(filePath);
            Scanner in =new Scanner(fichier);
            while(in.hasNextLine()){
                String ligne = in.nextLine();
                System.out.println(ligne);
               //  System.out.println("etape :");
                 if(ligne.startsWith("Nature:")){
                    System.out.println(ligne);
                    System.out.println(ligne.split(" ")[1]);
                    params.setNature(ligne.split(" ")[1]);
                    if (("RFT").equals(ligne.split(" ")[1])) {
                        RFTCheck.setSelected(true);
                        CadrePnl.setVisible(true);
                    }else if (("VVS").equals(ligne.split(" ")[1])){
                        VVSCheck.setSelected(true);
                    }else if (("AXE").equals(ligne.split(" ")[1])){
                        AxeCheck.setSelected(true);
                    }

                    //System.out.println("Bonjour");
                }
                  if(ligne.startsWith("Vitesse: ")){
                    System.out.println(ligne);
                    System.out.println(ligne.split(" ")[1]);
                    params.setVitesse(Double.parseDouble(ligne.split(" ")[1]));
                    Vitesse.setText(ligne.split(" ")[1]);
                }
                  if(ligne.startsWith("Orientations Initiales Baguette [")){
                       
                            //System.out.println("test");
                            String tot = ligne.split(" ")[3];
                            tot = tot.substring(1, tot.length() - 1);
                            
                            String[] tat = tot.split(";");
                           int len_B = tat.length;
                           System.out.println("len_B"+len_B);
                           int[] B = new int[len_B] ;
                         
                            for (String t: tat) {
                               System.out.println(t);
                                System.out.println("K :"+k);
                               B[k]= Integer.parseInt(t);
                                k=k+1;
                            }
                            
                            System.out.println("B[0] : "+B[0]);
                            params.setValeursTige(B);
                            ((DefaultTableModel) EssaisTige.getModel()).setRowCount(B.length);
                           
                                for (k=0; k<(B.length+1);k++){
                                    
                                
                                 EssaisTige.getModel().setValueAt(B[k], k, 0);
                                             
                                }                              
                                System.out.println("A[K] :"+B[k]);                                                      
                 }
                    
                
            }
              in.close();
        } catch (Exception ex){
            System.err.println("Error. "+ex.getMessage());
        }
          
    }
/************************************************************************************************************************************************/      
      public void readfiletest(String filePath){
        try {
            File fichier = new File(filePath);
            Scanner in =new Scanner(fichier);
            while(in.hasNextLine()){
                String ligne = in.nextLine();
                
                 if(ligne.startsWith("Aléatoire Baguette: ")){
                    System.out.println(ligne);
                    System.out.println(ligne.split(" ")[2]);
                    if (("OUI").equals(ligne.split(" ")[2])){
                        params.setAleatoireTige(true);
                        AleatoireCheckTige.setSelected(true);
                        ContinueCheckTige.setSelected(false);
                    }else {
                        params.setAleatoireTige(false);
                        AleatoireCheckTige.setSelected(false);
                        ContinueCheckTige.setSelected(true);
                    }
                 }
                 if(ligne.startsWith("Nombres de Répétition Baguette: ")){
                    System.out.println(ligne);
                    System.out.println(ligne.substring(7, 8));
                 //   params.setNombredEssai(Integer.parseInt(ligne.split(" ")[4]));
                     NombreEssaiTige.setText(ligne.split(" ")[4]);
                    }
                 if(ligne.startsWith("Orientations Initiales Cadre [")){
                      System.out.println("test");
                            String toto = ligne.split(" ")[3];
                            toto = toto.substring(1, toto.length() - 1);
                            
                            String[] tata = toto.split(";");
                           int len_A = tata.length;
                           System.out.println("len_A "+len_A);
                           int[] A = new int[len_A] ; 
                           for (String t: tata) {
                           System.out.println(t);
                           System.out.println("i: "+i);
                           A[i]= Integer.parseInt(t);
                           i=i+1;
                            }
                            System.out.println("A[0] : "+A[0]);
                            params.setValeursCadre(A);
                            ((DefaultTableModel) EssaisCadre.getModel()).setRowCount(A.length);
                           
                                for (i=0; i<(A.length);i++){
                                 EssaisCadre.getModel().setValueAt(A[i], i, 0);
                                 //System.out.println("bonjour");              
                                }           
                }
                 
            }
             in.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
/*****************************************************************************************************************************************************/
      public void readfiletest1 (String filePath){
        try {
            File fichier = new File(filePath);
            Scanner in =new Scanner(fichier);
            while(in.hasNextLine()){
                String ligne = in.nextLine();
                if(ligne.startsWith("Nombres de Répétition Cadre: ")){
                    System.out.println(ligne);
                    System.out.println(ligne.split(" ")[4]);
//                    params.setNombredEssai(Integer.parseInt(ligne.split(" ")[4]));
                    NombreEssaiCadre.setText(ligne.split(" ")[4]);
                }
                 if(ligne.startsWith("Aléatoire Cadre: ")){
                    System.out.println(ligne);
                    System.out.println(ligne.split(" ")[2]);
                    if (("OUI").equals(ligne.split(" ")[2])){
                        params.setAleatoireCadre(true);
                        AleatoireCheckCadre.setSelected(true);
                        ContinueCheckCadre.setSelected(false);
                    }else {
                        params.setAleatoireCadre(false);
                        AleatoireCheckCadre.setSelected(false);
                        ContinueCheckCadre.setSelected(true);
                    }
                 }
            }
             in.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
        }
          
      }
      
/************************************************************************************************************************************************/
      public void Valeurs (){
          int Net = Integer.parseInt(NombreEssaiTige.getText());
          int Nec ;
          int Et = EssaisTige.getRowCount();
          int Ec ;
          
        
        if (RFTCheck.isSelected()){
            Nec = Integer.parseInt(NombreEssaiCadre.getText());
            Ec = EssaisCadre.getRowCount();
            
        }else {
           
            Nec=1;
            Ec=1; 
        }
            e = Nec*Net*Ec*Et;
        
         
        String f = String.valueOf(e); 
        
        Nombredessai.setText(f);
        
        
          String Envoi[] = new String[e];
     
      }
      /*******************************************************************************************************************************************/

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        Zero = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        Confirmer = new javax.swing.JToggleButton();
        Valeur_zero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ErreurNature = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ErreurVitesse = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ErreurNbCadre = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        ErreurNbTige = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ErreurACadre = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        ErreurATige = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        RFTCheck = new javax.swing.JCheckBox();
        VVSCheck = new javax.swing.JCheckBox();
        AxeCheck = new javax.swing.JCheckBox();
        Envoyer = new javax.swing.JButton();
        BaguettePnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EssaisTige = new javax.swing.JTable();
        Nouveau_Tige = new javax.swing.JButton();
        NombreEssaiTige = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AleatoireCheckTige = new javax.swing.JCheckBox();
        ContinueCheckTige = new javax.swing.JCheckBox();
        SupprimerLigneTige = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CadrePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EssaisCadre = new javax.swing.JTable();
        SupprimmerLigneCadre = new javax.swing.JButton();
        OrientationCadres = new javax.swing.JLabel();
        NombreEssaiCadre = new javax.swing.JTextField();
        NombreRep = new javax.swing.JLabel();
        ContinueCheckCadre = new javax.swing.JCheckBox();
        AleatoireCheckCadre = new javax.swing.JCheckBox();
        Nouveau_Cadre1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Vitesse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombredessai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        OuvrirJmenu = new javax.swing.JMenuItem();
        Enregistrer = new javax.swing.JMenuItem();
        EnregistrerSous = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Nombres_Valeurs = new javax.swing.JMenuItem();

        Info.setMinimumSize(new java.awt.Dimension(840, 262));
        Info.setPreferredSize(new java.awt.Dimension(822, 262));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/imogy.png"))); // NOI18N
        jLabel6.setText(" A l'aide de la manette, placer la baguette à la Verticale gravitaire.");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Suivant");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout InfoLayout = new javax.swing.GroupLayout(Info.getContentPane());
        Info.getContentPane().setLayout(InfoLayout);
        InfoLayout.setHorizontalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        InfoLayout.setVerticalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        Zero.setMinimumSize(new java.awt.Dimension(766, 276));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        Confirmer.setBackground(new java.awt.Color(255, 255, 255));
        Confirmer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Confirmer.setText("Confimer");
        Confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmerActionPerformed(evt);
            }
        });

        Valeur_zero.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("  Précisez la valeur de référence de l'ajustement :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Confirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Valeur_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valeur_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Confirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout ZeroLayout = new javax.swing.GroupLayout(Zero.getContentPane());
        Zero.getContentPane().setLayout(ZeroLayout);
        ZeroLayout.setHorizontalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ZeroLayout.setVerticalGroup(
            ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurNature.setMinimumSize(new java.awt.Dimension(648, 228));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel10.setText("   Vous devez choisir un test !");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErreurNatureLayout = new javax.swing.GroupLayout(ErreurNature.getContentPane());
        ErreurNature.getContentPane().setLayout(ErreurNatureLayout);
        ErreurNatureLayout.setHorizontalGroup(
            ErreurNatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurNatureLayout.setVerticalGroup(
            ErreurNatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurVitesse.setMinimumSize(new java.awt.Dimension(727, 228));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel11.setText("   Vous devez indiquer la vitesse de rotation de la baguette !");

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout ErreurVitesseLayout = new javax.swing.GroupLayout(ErreurVitesse.getContentPane());
        ErreurVitesse.getContentPane().setLayout(ErreurVitesseLayout);
        ErreurVitesseLayout.setHorizontalGroup(
            ErreurVitesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurVitesseLayout.setVerticalGroup(
            ErreurVitesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurNbCadre.setMinimumSize(new java.awt.Dimension(674, 228));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel12.setText("  Vous devez indiquer le nombre de répétition pour le cadre !");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErreurNbCadreLayout = new javax.swing.GroupLayout(ErreurNbCadre.getContentPane());
        ErreurNbCadre.getContentPane().setLayout(ErreurNbCadreLayout);
        ErreurNbCadreLayout.setHorizontalGroup(
            ErreurNbCadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurNbCadreLayout.setVerticalGroup(
            ErreurNbCadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurNbTige.setMinimumSize(new java.awt.Dimension(665, 228));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel13.setText("  Vous devez indiquer le nombre de répétition pour la baguette !");

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErreurNbTigeLayout = new javax.swing.GroupLayout(ErreurNbTige.getContentPane());
        ErreurNbTige.getContentPane().setLayout(ErreurNbTigeLayout);
        ErreurNbTigeLayout.setHorizontalGroup(
            ErreurNbTigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurNbTigeLayout.setVerticalGroup(
            ErreurNbTigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurACadre.setMinimumSize(new java.awt.Dimension(670, 228));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel14.setText("   Vous devez préciser l'ordre de présentation pour le cadre !");

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErreurACadreLayout = new javax.swing.GroupLayout(ErreurACadre.getContentPane());
        ErreurACadre.getContentPane().setLayout(ErreurACadreLayout);
        ErreurACadreLayout.setHorizontalGroup(
            ErreurACadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurACadreLayout.setVerticalGroup(
            ErreurACadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ErreurATige.setMinimumSize(new java.awt.Dimension(678, 228));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/637560.jpg"))); // NOI18N
        jLabel15.setText("   Vous devez préciser l'ordre de présentation pour la baguette !");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addComponent(jButton8)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout ErreurATigeLayout = new javax.swing.GroupLayout(ErreurATige.getContentPane());
        ErreurATige.getContentPane().setLayout(ErreurATigeLayout);
        ErreurATigeLayout.setHorizontalGroup(
            ErreurATigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErreurATigeLayout.setVerticalGroup(
            ErreurATigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Devah");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RFTCheck.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RFTCheck.setForeground(new java.awt.Color(0, 0, 0));
        RFTCheck.setText("RFT");
        RFTCheck.setOpaque(false);
        RFTCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFTCheckActionPerformed(evt);
            }
        });

        VVSCheck.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        VVSCheck.setForeground(new java.awt.Color(0, 0, 0));
        VVSCheck.setText("VVS");
        VVSCheck.setOpaque(false);
        VVSCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VVSCheckActionPerformed(evt);
            }
        });

        AxeCheck.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AxeCheck.setForeground(new java.awt.Color(0, 0, 0));
        AxeCheck.setText("AXE-Z");
        AxeCheck.setOpaque(false);
        AxeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AxeCheckActionPerformed(evt);
            }
        });

        Envoyer.setBackground(new java.awt.Color(204, 204, 204));
        Envoyer.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Envoyer.setForeground(new java.awt.Color(0, 0, 0));
        Envoyer.setText("Calibration");
        Envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvoyerActionPerformed(evt);
            }
        });

        BaguettePnl.setBackground(new java.awt.Color(255, 255, 255));
        BaguettePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Baguette", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        BaguettePnl.setForeground(new java.awt.Color(51, 51, 51));
        BaguettePnl.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  Orientation initiale :");

        EssaisTige.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EssaisTige.setForeground(new java.awt.Color(51, 51, 51));
        EssaisTige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {null}
            },
            new String [] {
                "Valeurs"
            }
        ));
        EssaisTige.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EssaisTige.setInheritsPopupMenu(true);
        EssaisTige.setName(""); // NOI18N
        EssaisTige.setNextFocusableComponent(NombreEssaiTige);
        EssaisTige.setShowHorizontalLines(false);
        EssaisTige.setShowVerticalLines(false);
        EssaisTige.setSurrendersFocusOnKeystroke(true);
        EssaisTige.setUpdateSelectionOnSort(false);
        EssaisTige.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(EssaisTige);
        EssaisTige.getAccessibleContext().setAccessibleName("");
        EssaisTige.getAccessibleContext().setAccessibleDescription("");

        Nouveau_Tige.setBackground(new java.awt.Color(255, 255, 255));
        Nouveau_Tige.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Nouveau_Tige.setForeground(new java.awt.Color(0, 0, 0));
        Nouveau_Tige.setText("+");
        Nouveau_Tige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nouveau_TigeActionPerformed(evt);
            }
        });

        NombreEssaiTige.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de répétition  : ");

        AleatoireCheckTige.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AleatoireCheckTige.setForeground(new java.awt.Color(0, 0, 0));
        AleatoireCheckTige.setText("Aléatoire");
        AleatoireCheckTige.setOpaque(false);
        AleatoireCheckTige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatoireCheckTigeActionPerformed(evt);
            }
        });

        ContinueCheckTige.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ContinueCheckTige.setForeground(new java.awt.Color(0, 0, 0));
        ContinueCheckTige.setText("En bloc");
        ContinueCheckTige.setOpaque(false);
        ContinueCheckTige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueCheckTigeActionPerformed(evt);
            }
        });

        SupprimerLigneTige.setBackground(new java.awt.Color(255, 255, 255));
        SupprimerLigneTige.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SupprimerLigneTige.setForeground(new java.awt.Color(0, 0, 0));
        SupprimerLigneTige.setText("-");
        SupprimerLigneTige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerLigneTigeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ordre de présentation :");

        javax.swing.GroupLayout BaguettePnlLayout = new javax.swing.GroupLayout(BaguettePnl);
        BaguettePnl.setLayout(BaguettePnlLayout);
        BaguettePnlLayout.setHorizontalGroup(
            BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaguettePnlLayout.createSequentialGroup()
                .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(BaguettePnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BaguettePnlLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(AleatoireCheckTige)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContinueCheckTige))
                            .addGroup(BaguettePnlLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(NombreEssaiTige))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BaguettePnlLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Nouveau_Tige)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SupprimerLigneTige, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        BaguettePnlLayout.setVerticalGroup(
            BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaguettePnlLayout.createSequentialGroup()
                .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaguettePnlLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Nouveau_Tige)
                                .addComponent(SupprimerLigneTige))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreEssaiTige, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(BaguettePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AleatoireCheckTige)
                    .addComponent(ContinueCheckTige)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        CadrePnl.setBackground(new java.awt.Color(255, 255, 255));
        CadrePnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        CadrePnl.setOpaque(false);

        EssaisCadre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EssaisCadre.setForeground(new java.awt.Color(51, 51, 51));
        EssaisCadre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Valeurs"
            }
        ));
        jScrollPane1.setViewportView(EssaisCadre);

        SupprimmerLigneCadre.setBackground(new java.awt.Color(255, 255, 255));
        SupprimmerLigneCadre.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SupprimmerLigneCadre.setForeground(new java.awt.Color(0, 0, 0));
        SupprimmerLigneCadre.setText("-");
        SupprimmerLigneCadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimmerLigneCadreActionPerformed(evt);
            }
        });

        OrientationCadres.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        OrientationCadres.setForeground(new java.awt.Color(0, 0, 0));
        OrientationCadres.setText("  Orientation initiale :");

        NombreEssaiCadre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        NombreRep.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NombreRep.setForeground(new java.awt.Color(0, 0, 0));
        NombreRep.setText("Nombre de répétition  : ");

        ContinueCheckCadre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ContinueCheckCadre.setForeground(new java.awt.Color(0, 0, 0));
        ContinueCheckCadre.setText("En bloc");
        ContinueCheckCadre.setOpaque(false);
        ContinueCheckCadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueCheckCadreActionPerformed(evt);
            }
        });

        AleatoireCheckCadre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AleatoireCheckCadre.setForeground(new java.awt.Color(0, 0, 0));
        AleatoireCheckCadre.setText("Aléatoire");
        AleatoireCheckCadre.setOpaque(false);
        AleatoireCheckCadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatoireCheckCadreActionPerformed(evt);
            }
        });

        Nouveau_Cadre1.setBackground(new java.awt.Color(255, 255, 255));
        Nouveau_Cadre1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Nouveau_Cadre1.setForeground(new java.awt.Color(0, 0, 0));
        Nouveau_Cadre1.setText("+");
        Nouveau_Cadre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nouveau_Cadre1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Ordre de présentation :");

        javax.swing.GroupLayout CadrePnlLayout = new javax.swing.GroupLayout(CadrePnl);
        CadrePnl.setLayout(CadrePnlLayout);
        CadrePnlLayout.setHorizontalGroup(
            CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadrePnlLayout.createSequentialGroup()
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadrePnlLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrientationCadres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CadrePnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadrePnlLayout.createSequentialGroup()
                        .addComponent(AleatoireCheckCadre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContinueCheckCadre)
                        .addGap(99, 99, 99))
                    .addGroup(CadrePnlLayout.createSequentialGroup()
                        .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(NombreEssaiCadre, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addComponent(Nouveau_Cadre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SupprimmerLigneCadre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        CadrePnlLayout.setVerticalGroup(
            CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadrePnlLayout.createSequentialGroup()
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadrePnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OrientationCadres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreRep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreEssaiCadre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AleatoireCheckCadre)
                    .addComponent(ContinueCheckCadre))
                .addContainerGap())
            .addGroup(CadrePnlLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(CadrePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nouveau_Cadre1)
                    .addComponent(SupprimmerLigneCadre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Vitesse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Vitesse.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Vit. Baguette  :");

        Nombredessai.setBackground(new java.awt.Color(255, 255, 255));
        Nombredessai.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Nombredessai.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Choix du Test :");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("Nombre d'essai :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("deg/s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(243, 243, 243)
                            .addComponent(Envoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BaguettePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(RFTCheck)
                                    .addGap(18, 18, 18)
                                    .addComponent(VVSCheck)
                                    .addGap(18, 18, 18)
                                    .addComponent(AxeCheck)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(CadrePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(Vitesse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombredessai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Envoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VVSCheck)
                                .addComponent(AxeCheck)
                                .addComponent(Vitesse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(RFTCheck)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaguettePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CadrePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombredessai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)))
                .addGap(103, 103, 103))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu6.setBackground(new java.awt.Color(153, 153, 153));
        jMenu6.setForeground(new java.awt.Color(0, 0, 0));
        jMenu6.setText("Fichier ");

        OuvrirJmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OuvrirJmenu.setBackground(new java.awt.Color(153, 153, 153));
        OuvrirJmenu.setForeground(new java.awt.Color(0, 0, 0));
        OuvrirJmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icon_open.png"))); // NOI18N
        OuvrirJmenu.setText("Ouvrir");
        OuvrirJmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OuvrirJmenuActionPerformed(evt);
            }
        });
        jMenu6.add(OuvrirJmenu);

        Enregistrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Enregistrer.setBackground(new java.awt.Color(153, 153, 153));
        Enregistrer.setForeground(new java.awt.Color(0, 0, 0));
        Enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Save-icon.jpg"))); // NOI18N
        Enregistrer.setText("Enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });
        jMenu6.add(Enregistrer);

        EnregistrerSous.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        EnregistrerSous.setBackground(new java.awt.Color(153, 153, 153));
        EnregistrerSous.setForeground(new java.awt.Color(0, 0, 0));
        EnregistrerSous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Save-icon.jpg"))); // NOI18N
        EnregistrerSous.setText("Enregistrer Sous...");
        EnregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerSousActionPerformed(evt);
            }
        });
        jMenu6.add(EnregistrerSous);

        jMenuBar1.add(jMenu6);

        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Edit");

        Nombres_Valeurs.setBackground(new java.awt.Color(153, 153, 153));
        Nombres_Valeurs.setForeground(new java.awt.Color(51, 51, 51));
        Nombres_Valeurs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/eye-icon.jpg"))); // NOI18N
        Nombres_Valeurs.setText("Nombres de Valeurs");
        Nombres_Valeurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombres_ValeursActionPerformed(evt);
            }
        });
        jMenu1.add(Nombres_Valeurs);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimmerLigneCadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimmerLigneCadreActionPerformed
        // TODO add your handling code here:
       int  i = EssaisCadre.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) EssaisCadre.getModel();
       model.removeRow(i);
       
    }//GEN-LAST:event_SupprimmerLigneCadreActionPerformed

    private void Nouveau_TigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nouveau_TigeActionPerformed
        // TODO add your handling code here:
        i = EssaisTige.getRowCount();
        i=i+1;
        ((DefaultTableModel) EssaisTige.getModel()).setRowCount(i);
    }//GEN-LAST:event_Nouveau_TigeActionPerformed

    private void ContinueCheckTigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueCheckTigeActionPerformed
        // TODO add your handling code here:
        Aleatoire= false;
         params.setAleatoireTige(Aleatoire);
         AleatoireCheckTige.setSelected(false);
        c = "NON";
    }//GEN-LAST:event_ContinueCheckTigeActionPerformed

    private void AleatoireCheckTigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatoireCheckTigeActionPerformed
        // TODO add your handling code here:
        Aleatoire = true ;
        ContinueCheckTige.setSelected(false);
        c="OUI";
        params.setAleatoireTige(Aleatoire);
    }//GEN-LAST:event_AleatoireCheckTigeActionPerformed

    private void AxeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AxeCheckActionPerformed
        // TODO add your handling code here:
        a= "AXE-Z";
        RFTCheck.setSelected(false);
        VVSCheck.setSelected(false);
        CadrePnl.setVisible(false);
    
        jPanel1.setSize(1177, 816);
        
    }//GEN-LAST:event_AxeCheckActionPerformed

    private void VVSCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VVSCheckActionPerformed
        // TODO add your handling code here:
        a= "VVS";
        RFTCheck.setSelected(false);
        AxeCheck.setSelected(false);
        CadrePnl.setVisible(false);
         
       jPanel1.setSize(1177, 816);
       
    }//GEN-LAST:event_VVSCheckActionPerformed

    private void RFTCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFTCheckActionPerformed
        // TODO add your handling code here:
        a="RFT";
        
        VVSCheck.setSelected(false);
        AxeCheck.setSelected(false);
        CadrePnl.setVisible(true);
        
       jPanel1.setSize(1177, 816);
        
        
    }//GEN-LAST:event_RFTCheckActionPerformed

    private void OuvrirJmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuvrirJmenuActionPerformed
        // TODO add your handling code here:
            JFileChooser ch=new JFileChooser();
        int var = ch .showOpenDialog(null);
//        Chemin.setText(ch.getSelectedFile().getAbsolutePath());
        readFile(ch.getSelectedFile().getAbsolutePath());
         readfiletest(ch.getSelectedFile().getAbsolutePath());
         readfiletest1(ch.getSelectedFile().getAbsolutePath());
        
    }//GEN-LAST:event_OuvrirJmenuActionPerformed

    private void ContinueCheckCadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueCheckCadreActionPerformed
        // TODO add your handling code here:
        b="NON";     
        AleatoireCheckCadre.setSelected(false);
        params.setAleatoireCadre(false);
    }//GEN-LAST:event_ContinueCheckCadreActionPerformed

    private void AleatoireCheckCadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatoireCheckCadreActionPerformed
        //Aléatoire Cadre 
        b="OUI";
       ContinueCheckCadre.setSelected(false);
       params.setAleatoireCadre(true);
        
    }//GEN-LAST:event_AleatoireCheckCadreActionPerformed

    private void EnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerSousActionPerformed
        // TODO add your handling code here:
        final JFrame fenetre = new JFrame();
        fenetre.setSize(200,200);
        fenetre.setLocationRelativeTo(null);
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(false);

        JFileChooser fc = new JFileChooser();
         int val_retour = fc.showSaveDialog(fc);
            
             //if (val_retour == JFileChooser.APPROVE_OPTION) {
            try {
              
                File fichier1 = fc.getSelectedFile();
                File fi = new File(fichier1.getAbsolutePath());
                fi.createNewFile();
            PrintWriter fichier = new PrintWriter(fichier1.getAbsolutePath());
            fichier.println("Nature: " +a );
            fichier.println("Vitesse: " + Vitesse.getText());
            fichier.println("-----------------------------------");
            fichier.print("Orientations Initiales Baguette [");
            for(i=0;i <EssaisTige.getRowCount();i++){
                if (i!=(EssaisTige.getRowCount()-1)){
                    
                    fichier.print(String.valueOf( EssaisTige.getModel().getValueAt(i,0))+";");
                } else {
                    fichier.print(String.valueOf( EssaisTige.getModel().getValueAt(i,0)));
                    
                }
            }
            fichier.println("]");
            fichier.println("Aléatoire Baguette: "+c);
            fichier.println("Nombres de Répétition Baguette: "+NombreEssaiTige.getText());
            fichier.println("-----------------------------------");
            fichier.print("Orientations Initiales Cadre [");
            for(i=0;i <EssaisCadre.getRowCount();i++){
                if (i!=(EssaisCadre.getRowCount()-1)){
                    
                    fichier.print(String.valueOf( EssaisCadre.getModel().getValueAt(i,0))+";");
                } else {
                    fichier.print(String.valueOf( EssaisCadre.getModel().getValueAt(i,0)));
                    
                }
            }
            fichier.println("]");
            fichier.println("Aléatoire Cadre: "+b);
            fichier.println("Nombres de Répétition Cadre: "+NombreEssaiCadre.getText());
            fichier.println("--------------------------------------");
            fichier.println("Nombres d'éssais: "+ Nombredessai.getText());
            fichier.close();
                //afficher le chemin absolu du fichier
                
                System.out.println("Chemin absolu : "+fichier1.getAbsolutePath()+"\n");
                
            } catch (IOException ex) {
                Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
            }
            /* } else {
                  System.out.println("L'enregistrement est annulée\n");
             }*/
    }//GEN-LAST:event_EnregistrerSousActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
       Enregistrement();

    }//GEN-LAST:event_EnregistrerActionPerformed

    
    
    private void EnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvoyerActionPerformed
            //Enregistrement();
        erreur();
         Valeurs();
         System.out.print(EssaisCadre.getRowCount());
         Alea();
         Info.setVisible(true);
         Info.setTitle("Calibration");
    }//GEN-LAST:event_EnvoyerActionPerformed

    private void Nombres_ValeursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombres_ValeursActionPerformed
    Valeurs();
    }//GEN-LAST:event_Nombres_ValeursActionPerformed

    private void ConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmerActionPerformed
        
            /*  final JFrame fenetre = new JFrame();
            fenetre.setSize(200,200);
            fenetre.setLocationRelativeTo(null);
            fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            fenetre.setVisible(false);
            
            JFileChooser fc = new JFileChooser();
            int val_retour = fc.showSaveDialog(fc);
            
            //if (val_retour == JFileChooser.APPROVE_OPTION) {
            try {
            
            File fichier1 = fc.getSelectedFile();
            File fi = new File(fichier1.getAbsolutePath());
            fi.createNewFile();
            PrintWriter fichier = new PrintWriter(fichier1.getAbsolutePath());
            fichier.println("Nature: " +a );
            fichier.println("Vitesse: " + Vitesse.getText());
            fichier.println("-----------------------------------");
            fichier.print("Orientations Initiales Baguette [");
            for(i=0;i <EssaisTige.getRowCount();i++){
            if (i!=(EssaisTige.getRowCount()-1)){
            
            fichier.print(String.valueOf( EssaisTige.getModel().getValueAt(i,0))+";");
            } else {
            fichier.print(String.valueOf( EssaisTige.getModel().getValueAt(i,0)));
            
            }
            }
            fichier.println("]");
            fichier.println("Aléatoire Baguette: "+c);
            fichier.println("Nombres de Répétition Baguette: "+NombreEssaiTige.getText());
            fichier.println("-----------------------------------");
            fichier.print("Orientations Initiales Cadre [");
            for(i=0;i <EssaisCadre.getRowCount();i++){
            if (i!=(EssaisCadre.getRowCount()-1)){
            
            fichier.print(String.valueOf( EssaisCadre.getModel().getValueAt(i,0))+";");
            } else {
            fichier.print(String.valueOf( EssaisCadre.getModel().getValueAt(i,0)));
            
            }
            }
            fichier.println("]");
            fichier.println("Aléatoire Cadre: "+b);
            fichier.println("Nombres de Répétition Cadre: "+NombreEssaiCadre.getText());
            fichier.println("--------------------------------------");
            fichier.println("Nombres d'éssais: "+ Nombredessai.getText());
            fichier.println("Zéro: " + Valeur_zero.getText());
            fichier.close();
            //afficher le chemin absolu du fichier
            
            System.out.println("Chemin absolu : "+fichier1.getAbsolutePath()+"\n");
            
            } catch (IOException ex) {
            Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            params.setOrientationInitiales(Integer.parseInt(Valeur_zero.getText()));
            Valeurs();
            params.setReference(Integer.parseInt( Valeur_zero.getText()));
            
                   
        if (RFTCheck.isSelected()){
            ValeurCadre vc = new ValeurCadre();
            vc.setVisible(true);
            Zero.hide();
        }else{
            Suivant sv = new Suivant();
            sv.setVisible(true);
            Zero.hide();
        }
    }//GEN-LAST:event_ConfirmerActionPerformed

    private void SupprimerLigneTigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerLigneTigeActionPerformed
       
        int  i = EssaisTige.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) EssaisTige.getModel();
       model.removeRow(i);
    }//GEN-LAST:event_SupprimerLigneTigeActionPerformed

    private void Nouveau_Cadre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nouveau_Cadre1ActionPerformed
     // TODO add your handling code here:
        i = EssaisCadre.getRowCount();
        i=i+1;
        ((DefaultTableModel) EssaisCadre.getModel()).setRowCount(i);
    }//GEN-LAST:event_Nouveau_Cadre1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          int Net = Integer.parseInt(NombreEssaiTige.getText());
          int Nec ;
        
          int Et = EssaisTige.getRowCount();
          int Ec ;
          int e ;
        
        if (RFTCheck.isSelected()){
            Nec = Integer.parseInt(NombreEssaiCadre.getText());
            Ec = EssaisCadre.getRowCount();
            
        }else {
           
            Nec=1;
            Ec=1; 
        }
            e = Nec*Net*Ec*Et;
        
         
        String f = String.valueOf(e); 
        
        
        Nombredessai.setText(f);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Info.dispose();
        if(AxeCheck.isSelected()){
            Zero.setVisible(true);
        Zero.setTitle("Valeur de Réference");
        }else 
        if (RFTCheck.isSelected()){
            ValeurCadre vc = new ValeurCadre();
            vc.setVisible(true);
            Zero.hide();
        }else{
            Suivant sv = new Suivant();
            sv.setVisible(true);
            Zero.hide();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ErreurNature.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ErreurVitesse.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     ErreurNbCadre.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ErreurNbTige.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ErreurACadre.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ErreurATige.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             Save sav =   new Save();
                     sav.setVisible(true);
                try { 
   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); 
   SwingUtilities.updateComponentTreeUI(sav); 
   //force chaque composant de la fenêtre à appeler sa méthode updateUI 
} catch (InstantiationException e) { 
} catch (ClassNotFoundException e) { 
} catch (UnsupportedLookAndFeelException e) { 
} catch (IllegalAccessException e) {}
            }
        });
    }

boolean Aleatoire;
int i;
int j;
int k;
String  b ;
String c; 
boolean p;
int e ;
 public int[] Cadre;
public int [] Tige;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox AleatoireCheckCadre;
    public javax.swing.JCheckBox AleatoireCheckTige;
    public javax.swing.JCheckBox AxeCheck;
    private javax.swing.JPanel BaguettePnl;
    public javax.swing.JPanel CadrePnl;
    private javax.swing.JToggleButton Confirmer;
    public javax.swing.JCheckBox ContinueCheckCadre;
    private javax.swing.JCheckBox ContinueCheckTige;
    private javax.swing.JMenuItem Enregistrer;
    private javax.swing.JMenuItem EnregistrerSous;
    private javax.swing.JButton Envoyer;
    private javax.swing.JDialog ErreurACadre;
    private javax.swing.JDialog ErreurATige;
    private javax.swing.JDialog ErreurNature;
    private javax.swing.JDialog ErreurNbCadre;
    private javax.swing.JDialog ErreurNbTige;
    private javax.swing.JDialog ErreurVitesse;
    public javax.swing.JTable EssaisCadre;
    public javax.swing.JTable EssaisTige;
    private javax.swing.JDialog Info;
    public javax.swing.JTextField NombreEssaiCadre;
    public javax.swing.JTextField NombreEssaiTige;
    private javax.swing.JLabel NombreRep;
    private javax.swing.JLabel Nombredessai;
    private javax.swing.JMenuItem Nombres_Valeurs;
    private javax.swing.JButton Nouveau_Cadre1;
    public javax.swing.JButton Nouveau_Tige;
    private javax.swing.JLabel OrientationCadres;
    private javax.swing.JMenuItem OuvrirJmenu;
    public javax.swing.JCheckBox RFTCheck;
    public javax.swing.JButton SupprimerLigneTige;
    private javax.swing.JButton SupprimmerLigneCadre;
    public javax.swing.JCheckBox VVSCheck;
    private javax.swing.JTextField Valeur_zero;
    public javax.swing.JTextField Vitesse;
    private javax.swing.JDialog Zero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    
}
