/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Parametre;
import arduino.Arduino;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Teamatio
 */
public class Suivant extends javax.swing.JFrame {

    /**
     * Creates new form Suivant
     */
    Classes.Parametre params = new Classes.Parametre();
    int A[];
    int B[];
    String C ; 
    int D;
    String E[];
    String a;
    static String inputLine="2";
    Vector<String> V = new Vector<String>();
    static Vector<String> R = new Vector<String>();
    String [] Valeu = new String[D];
   static  Arduino ardu = new Arduino();
    public Suivant() {
        initComponents();
        setTitle("Résultats en cours");
         ardu.setPortDescription("COM7");
         ardu.setBaudRate(57600);
         B= params.getValeursTige();
         C=params.getNature();
         D=params.getNombresTotal();
          val();
        table();
        centerTable();
         
       
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vale = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Valeur_recu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ValeurTable = new javax.swing.JTable();

        vale.setAlwaysOnTop(true);
        vale.setMinimumSize(new java.awt.Dimension(633, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Valeur :");

        jButton2.setText("Terminé");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Valeur_recu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Valeur_recu.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valeur_recu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valeur_recu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout valeLayout = new javax.swing.GroupLayout(vale.getContentPane());
        vale.getContentPane().setLayout(valeLayout);
        valeLayout.setHorizontalGroup(
            valeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        valeLayout.setVerticalGroup(
            valeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setText("Essai suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ValeurTable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ValeurTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° de l'essai", "Orientation init. de la Baguette (deg)", "Orientation finale de la baguette (deg)", "Temps d'ajustement (ms) ", "Invalidation de l'essai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ValeurTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(964, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                    .addGap(72, 72, 72)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(499, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void val(){
       
         
         System.out.println(D);        
             for(int m =0;m<B.length;m++){
                 V.addElement(C+":"+B[m]);     
             }
             
         
          System.out.println("valeur"+V.size());
        
     }
public void table(){
         ((DefaultTableModel) ValeurTable.getModel()).setRowCount(V.size());
         for(int i=0; i<V.size();i++){
             ValeurTable.setValueAt(i+1,i, 0);
             ValeurTable.setValueAt(V.get(i).split(":")[1], i, 1); 
            
         }
     }
    /**
     *
     */
     public void centerTable() {
            DefaultTableCellRenderer custom = new DefaultTableCellRenderer(); 
            custom.setHorizontalAlignment(JLabel.CENTER); // centre les données de ton tableau
             for (int i=0 ; i < ValeurTable.getColumnCount() ; i++){ // centre chaque cellule de ton tableau
                ValeurTable.getColumnModel().getColumn(i).setCellRenderer(custom); 
            }
            
        }
    public   void get(){
      
            ardu.openConnection();
            
            
            a =ardu.serialRead();
            Valeur_recu.setText(a);
            ValeurTable.setValueAt(a, i-1, 2);
            System.out.println(a);
            
       
       
    }
    Timer timer = new Timer(200, new ActionListener() {
   public void actionPerformed(ActionEvent ae) {
   get();
    if(ValeurTable.getValueAt(i-1, 1).equals(ValeurTable.getValueAt(i-1, 3))){
      ValeurTable.setValueAt("OK", i-1, 4);
        } 
   }
 });
 
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      try {
         
         val();
            ardu.openConnection();
            Thread.sleep(1000);
            
             if ( i <D){
                 
                 
                       ardu.serialWrite("Init:"+params.getReference());
                        System.out.println("Val: "+V.get(i));    
                     Thread.sleep(500);
                       ardu.serialWrite(V.get(i));
                        i++;
                        if (i==D){
                   jButton1.setText("Terminer");
               } 
                    
            }else {
                           
                 
                    final JFrame fenetre = new JFrame();
                    fenetre.setSize(200,200);
                    fenetre.setLocationRelativeTo(null);
                    fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    fenetre.setVisible(false);
                    JFileChooser fc = new JFileChooser();
                    int val_retour = fc.showSaveDialog(fc);
                    
                      File fichier1 = fc.getSelectedFile();
                File fi = new File(fichier1.getAbsolutePath()+".txt");
                fi.createNewFile();
            PrintWriter fichier = new PrintWriter(fichier1.getAbsolutePath()+".txt");
            fichier.println("Test: " +C );
            fichier.println("Vitesse d'ajustement: " + params.getVitesse());
            fichier.println("-----------------------------------");
            fichier.println("Bag. Orientation init.:"+Arrays.toString(B));
           
            
            fichier.println("Bag. Aléatoire: "+params.isAleatoireTige());
            fichier.println("Bag. Nombre de répétition: "+params.getNombredEssaiTige());
            fichier.println("-----------------------------------");
            fichier.println("Cadre Orientation init. : "+Arrays.toString(params.getValeursCadre()));
            
            fichier.println("Cadre Aléatoire: "+Parametre.isAleatoireCadre());
            fichier.println("Cadre Nombre de répétition: "+params.getNombredEssaiCadre());
            fichier.println("--------------------------------------");
            fichier.println("Nombre d'essai: "+D);
            fichier.println("Zéro:"+params.getReference());
            fichier.println("--------------------------------------");
            fichier.println("Résultats: {");
           for (int v=0;v<D;v++){
                fichier.println("--------------------------------------");
                //fichier.print(ValeurTable.getValueAt(v, 0));
                fichier.print(ValeurTable.getValueAt(v, 1));
                fichier.print("-->");
                fichier.print(ValeurTable.getValueAt(v, 2));
                fichier.print("-->");
                fichier.println(ValeurTable.getValueAt(v, 3));
                
              }
                fichier.println("}");

            fichier.close();
            System.exit(0);
             }
             
             
         //ardu.closeConnection();
          // Thread.sleep(1000);
           
        } catch (InterruptedException ex) {
            Logger.getLogger(ValeurCadre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Suivant.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
      
      
       timer.setRepeats(true);
       timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        R.add(Valeur_recu.getText());
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suivant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suivant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suivant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suivant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          
          
       
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Suivant().setVisible(true);
                 Valeur_recu.setText(inputLine); 
                System.out.println(inputLine);
               
            }
            
        });
        
    }
    
   
int i;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ValeurTable;
    public static javax.swing.JLabel Valeur_recu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JDialog vale;
    // End of variables declaration//GEN-END:variables
}
